### PR TITLE
Add support for SAML 1 Tokens

### PR DESCRIPTION
**Pull request by ebeigarts**
This is based on #12 with these additions:

- Rebased against master
- Support `saml_version` to be number or string (`1` or `"1"`)
- Support `ID` and `AssertionID`

### CODE REVIEW

**Comment by ebeigarts** [comment]
@kbeckman any change getting this merged in and relased to rubygems? I am already using this in production.

**Comment by kbeckman** [comment]
@ebeigarts, first of all let me thank you for your contribution... And my apologies for the delay on this.

I tested the initial pull request from @kcdragon quite extensively and could not get it to work through Azure ACS. ...and I didn't get many timely replies from that thread so I had to put it off. I haven't had the opportunity to test your PR yet, I had planned on getting around to this in February for another in-depth look. 

Here's what I can do until I'm able to circle back around on this officially... I'll take this PR and build a "0.3.0-beta" gem this weekend so you can get away from pointing to your fork in the Gemfile and I'll do the official release sometime in February. I hope that will get you going... ...and thank you again for your contribution!

**Comment by ebeigarts** [comment]
@kbeckman thanks, that would be great

**Comment by kbeckman** [comment]
Hi, @ebeigarts. I just pushed the `0.3.0-beta` version to rubygems.org

https://rubygems.org/gems/omniauth-wsfed/versions/0.3.0.pre.beta

**Comment by ebeigarts** [comment]
@kbeckman thanks

**Comment by ebeigarts** [comment]
@kbeckman you released `0.3.0.pre.beta` without my changes, they were merged in `development` branch and not in `master`, see https://github.com/kbeckman/omniauth-wsfed/network. What is the purpose for those two branches? most of the opensource projects just use `master`. It would be nice if you could also merge in #17 and release `0.3.0.rc1`.

**Comment by kbeckman** [comment]
The branching structure in this project is set up according to [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) like most other gems that follow [semantic versioning](http://semver.org/). I made a mistake with the merge and will get another build to ruby gems out shortly...

As far as [PR #17](https://github.com/kbeckman/omniauth-wsfed/pull/17), this was a small change with no associated test(s). If you'd like to add the tests to `spec/omniauth/strategies/wsfed/auth_request_spec.rb`, I'll include it in another build. Otherwise, it will have to wait until I can get the test(s) in sometime in February.

**Comment by kbeckman** [comment]
Version [0.3.1-beta](https://rubygems.org/gems/omniauth-wsfed/versions/0.3.1.pre.beta) has been released - this time with your changes... Sorry for the confusion.

**Comment by ebeigarts** [comment]
@kbeckman thanks, I will try to add tests for #17.

**Pull request merged**
